### ISSUE TITLE
mason on nixos?

### ISSUE THREAD

**Issue by Vaisakhkm2625** [henry40408/nixos-config#5]
https://github.com/henry40408/nixos-config/commit/9001d5ba7027bd08d7e08899fa5c4c614a6b74cc

did you managed to get mason working? or still manually adding lsp packages?

what does PATH="append" here do? https://github.com/henry40408/nixos-config/blob/9001d5ba7027bd08d7e08899fa5c4c614a6b74cc/home-manager/neovim/lua/plugins/mason.lua

**Comment by henry40408** [comment]
> did you managed to get mason working? or still manually adding lsp packages?

I manually add them via `extraPackages`. Packages installed by Mason cannot be invoked directly. More details can be found at https://github.com/williamboman/mason.nvim/issues/428 .

> what does PATH="append" here do?

The option asks Mason to add its bin location to the end of the PATH environment variable. However, since packages are installed by home-manager, it's actually irrelevant.
